version: '3.9'
name: 'altaira-dev'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./docker-data-dev/pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data:
    driver: local

networks:
  shared_network:
    external: true