version: '3.9'
name: 'altaira-monitoring'

services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    networks:
      - altaira_monitoring_network
    volumes:
      - ./docker-data/prometheus:/etc/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: always
    ports:
      - "${LOKI_PORT}:3100"
    networks:
      - altaira_monitoring_network
    volumes:
      - ./docker-data/loki:/etc/loki
      - ./docker-data/loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml


  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECURITY_ADMIN_PASS}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
      GF_SECURITY_DISABLE_GRAVATAR: 'true'
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      PROMETHEUS_URL: http://prometheus:${PROMETHEUS_PORT}
      LOKI_URL: http://loki:${LOKI_PORT}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker-data/grafana/provisioning:/etc/grafana/provisioning
      - ./docker-data/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - altaira_monitoring_network

volumes:
  grafana_data:
  loki:
  dev:
    driver: local
    driver_opts:
      type: none
      o: bind,delegated
      device: ${PWD}

networks:
  altaira_monitoring_network:
    driver: bridge
